/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentationLayer;

import businessLogicLayer.managingUser;
import dataAccessLayer.managingUserdaoimpl;
import dataAccessLayer.managingUserdao;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class Usermanagement extends javax.swing.JFrame {

    /**
     * Creates new form Usermanagement
     */
    public Usermanagement() {


        initComponents();

        details();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void details() {
        
        managingUser f = new managingUser();
        managingUserdao d = new managingUserdaoimpl();
        d.readbtnum(f);
        ArrayList<ArrayList<String>> a = new ArrayList();

        a = f.getData();
        String[] tdata = new String[a.get(0).size()];
        DefaultTableModel tbl = (DefaultTableModel) Usermanagement_table.getModel();
        for (int k = 0; k < a.size(); k++) {
            for (int j = 0; j < a.get(k).size(); j++) {

                tdata[j] = a.get(k).get(j);
            }
            tbl.addRow(tdata);

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        User_idum = new javax.swing.JTextField();
        Usernameum = new javax.swing.JTextField();
        Phonenoum = new javax.swing.JTextField();
        Emailum = new javax.swing.JTextField();
        Passwordum = new javax.swing.JPasswordField();
        Combousermanagement = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Usermanagement_table = new javax.swing.JTable();
        Addusermanagement = new javax.swing.JButton();
        Update_btnum = new javax.swing.JButton();
        Reset_btnum = new javax.swing.JButton();
        Delete_btnum = new javax.swing.JButton();
        Search_key = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Homepage_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Management Menu");

        jPanel1.setBackground(new java.awt.Color(111, 78, 55));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("User_id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("APU Cafeteria Ordering System");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Phone No.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Email");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Designation");

        Emailum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailumActionPerformed(evt);
            }
        });

        Passwordum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordumActionPerformed(evt);
            }
        });

        Combousermanagement.setBackground(new java.awt.Color(153, 153, 153));
        Combousermanagement.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Combousermanagement.setForeground(new java.awt.Color(51, 51, 51));
        Combousermanagement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Customer" }));
        Combousermanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombousermanagementActionPerformed(evt);
            }
        });

        Usermanagement_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_id", "Username", "Password", "Phone No.", "Email", "User Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Usermanagement_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Usermanagement_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Usermanagement_table);

        Addusermanagement.setBackground(new java.awt.Color(140, 98, 57));
        Addusermanagement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addusermanagement.setForeground(new java.awt.Color(255, 255, 255));
        Addusermanagement.setText("Add");
        Addusermanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddusermanagementActionPerformed(evt);
            }
        });

        Update_btnum.setBackground(new java.awt.Color(140, 98, 57));
        Update_btnum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_btnum.setForeground(new java.awt.Color(255, 255, 255));
        Update_btnum.setText("UPDATE");
        Update_btnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnumActionPerformed(evt);
            }
        });

        Reset_btnum.setBackground(new java.awt.Color(140, 98, 57));
        Reset_btnum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reset_btnum.setForeground(new java.awt.Color(255, 255, 255));
        Reset_btnum.setText("Reset");
        Reset_btnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnumActionPerformed(evt);
            }
        });

        Delete_btnum.setBackground(new java.awt.Color(140, 98, 57));
        Delete_btnum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_btnum.setForeground(new java.awt.Color(255, 255, 255));
        Delete_btnum.setText("Delete");
        Delete_btnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnumActionPerformed(evt);
            }
        });

        Search_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_keyActionPerformed(evt);
            }
        });
        Search_key.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_keyKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Provide Info to Search Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(75, 75, 75)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Passwordum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Phonenoum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(User_idum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Usernameum, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Search_key, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Combousermanagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Emailum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(Addusermanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update_btnum)
                .addGap(18, 18, 18)
                .addComponent(Reset_btnum)
                .addGap(18, 18, 18)
                .addComponent(Delete_btnum, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Search_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(User_idum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Usernameum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Passwordum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phonenoum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Emailum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete_btnum)
                            .addComponent(Reset_btnum)
                            .addComponent(Update_btnum)
                            .addComponent(Addusermanagement))
                        .addComponent(Combousermanagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Homepage_btn.setBackground(new java.awt.Color(140, 98, 57));
        Homepage_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Homepage_btn.setForeground(new java.awt.Color(255, 255, 255));
        Homepage_btn.setText("Back");
        Homepage_btn.setBorderPainted(false);
        Homepage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Homepage_btnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Used/logosmall.png"))); // NOI18N

        Backbtn.setBackground(new java.awt.Color(140, 98, 57));
        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage Users Detail");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(Homepage_btn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(Backbtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)))
                .addGap(379, 379, 379)
                .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(Homepage_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        jPanel1.getAccessibleContext().setAccessibleName("User Management");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Homepage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Homepage_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Homepage_btnActionPerformed

    private void Search_keyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_keyKeyReleased

        var Searchz = Search_key.getText();
        searche(Searchz);
    }//GEN-LAST:event_Search_keyKeyReleased

    private void Search_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_keyActionPerformed

    }//GEN-LAST:event_Search_keyActionPerformed

    private void Delete_btnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnumActionPerformed
        String record, username;
        managingUser hi = new managingUser();


        hi.setUsername(Usernameum.getText());

        File db = new File("Login.txt");
        File tempdb = new File("Logintmp.txt");

        BufferedReader br;
        try {
            br = new BufferedReader(new FileReader(db));
            BufferedWriter bw = new BufferedWriter(new FileWriter(tempdb));

            username = hi.getUsername();

            while ((record = br.readLine()) != null) {
                if (record.contains(username)) {
                    continue;
                }
                bw.write(record);
                bw.flush();
                bw.newLine();
            }
            br.close();
            bw.close();
            db.delete();

            tempdb.renameTo(db);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tbl = (DefaultTableModel) Usermanagement_table.getModel();
        if (Usermanagement_table.getSelectedRowCount() == 1) {
            tbl.removeRow(Usermanagement_table.getSelectedRow());
            JOptionPane.showMessageDialog(this, "The Data Has been Deleted Sucessfully.");

        } else {
            if (Usermanagement_table.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Empty Table Found");
            } else {
                JOptionPane.showMessageDialog(this, "Select the Row to Delete the record");
            }
        }
    }//GEN-LAST:event_Delete_btnumActionPerformed

    private void Reset_btnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnumActionPerformed
        // TODO add your handling code here:
        User_idum.setText(null);
        Usernameum.setText(null);
        Passwordum.setText(null);
        Phonenoum.setText(null);
        Emailum.setText(null);
        JOptionPane.showMessageDialog(this, "The Data Has been Reset.");
    }//GEN-LAST:event_Reset_btnumActionPerformed

    private void Update_btnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnumActionPerformed
        // TODO add your handling code here:
        managingUser hi = new managingUser();
        managingUserdao daoms = new managingUserdaoimpl();

        hi.setUsername(Usernameum.getText());
        hi.setPassword(Passwordum.getText());
        hi.setEmail(Emailum.getText());
        hi.setUserid(User_idum.getText());
        hi.setPhone(Integer.parseInt(Phonenoum.getText()));
        hi.setDesignation(Combousermanagement.getSelectedItem().toString());

        if (User_idum.getText().equals("") || User_idum.getText().equals("") || Usernameum.getText().equals("") || Passwordum.getText().equals("") || Phonenoum.getText().equals("") || Emailum.getText().equals("") || Combousermanagement.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(this, "Please Fill all the field to process.");
        } else {
            daoms.Updatebtnum(hi);

            int i = Usermanagement_table.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) Usermanagement_table.getModel();
            if (i >= 0) {
                model.setValueAt(User_idum.getText(), i, 0);
                model.setValueAt(Usernameum.getText(), i, 1);
                model.setValueAt(Passwordum.getText(), i, 2);
                model.setValueAt(Phonenoum.getText(), i, 3);
                model.setValueAt(Emailum.getText(), i, 4);
                model.setValueAt(Combousermanagement.getSelectedItem().toString(), i, 5);
                JOptionPane.showMessageDialog(this, "Data has been Successfully Updated.");
            } else {
                JOptionPane.showMessageDialog(this, "Error While Updating.");
            }

        }

    }//GEN-LAST:event_Update_btnumActionPerformed

    private void AddusermanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddusermanagementActionPerformed
        managingUser mso = new managingUser(); //BLL
        managingUserdao msd = new managingUserdaoimpl(); // DAO

        mso.setUsername(Usernameum.getText());
        mso.setPassword(Passwordum.getText());
        mso.setEmail(Emailum.getText());
        mso.setUserid(User_idum.getText());
        mso.setPhone(Integer.parseInt(Phonenoum.getText()));
        mso.setDesignation(Combousermanagement.getSelectedItem().toString());

        msd.addbtnum(mso, mso, mso, mso, mso, mso);
        String usname = mso.getUsername();
        String pass = mso.getPassword();
        String email = mso.getEmail();
        String useid = mso.getUserid();
        int phone = mso.getPhone();
        String design = mso.getDesignation();
        DefaultTableModel Model = (DefaultTableModel) Usermanagement_table.getModel();
        Object data[] = {useid, usname, pass, phone, email, design};
        Model.addRow(data);
        JOptionPane.showMessageDialog(this, "The Data Has been Added Sucessfully.");

    }//GEN-LAST:event_AddusermanagementActionPerformed

    private void Usermanagement_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Usermanagement_tableMouseClicked
        // To show the data after clickling the Table
        int i = Usermanagement_table.getSelectedRow();
        TableModel model = Usermanagement_table.getModel();
        User_idum.setText(model.getValueAt(i, 0).toString()); //The data is set to
        Usernameum.setText(model.getValueAt(i, 1).toString());
        Passwordum.setText(model.getValueAt(i, 2).toString());
        Phonenoum.setText(model.getValueAt(i, 3).toString());
        Emailum.setText(model.getValueAt(i, 4).toString());
        String combox = model.getValueAt(i, 5).toString();
        if (combox.equals("Manager")) {
            Combousermanagement.setSelectedIndex(0);
        } else if (combox.equals("Customer")) {
            Combousermanagement.setSelectedIndex(1);
        }

    }//GEN-LAST:event_Usermanagement_tableMouseClicked

    private void CombousermanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombousermanagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombousermanagementActionPerformed

    private void PasswordumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordumActionPerformed

    private void EmailumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailumActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        managerHome hey = new managerHome();
        hey.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbtnActionPerformed
    private void searche(String Str) {
        DefaultTableModel tablez = (DefaultTableModel) Usermanagement_table.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(tablez);
        Usermanagement_table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Str));

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usermanagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usermanagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addusermanagement;
    private javax.swing.JButton Backbtn;
    private javax.swing.JComboBox<String> Combousermanagement;
    private javax.swing.JButton Delete_btnum;
    private javax.swing.JTextField Emailum;
    private javax.swing.JButton Homepage_btn;
    private javax.swing.JPasswordField Passwordum;
    private javax.swing.JTextField Phonenoum;
    private javax.swing.JButton Reset_btnum;
    private javax.swing.JTextField Search_key;
    private javax.swing.JButton Update_btnum;
    private javax.swing.JTextField User_idum;
    private javax.swing.JTable Usermanagement_table;
    private javax.swing.JTextField Usernameum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
